# Generated by Django 5.2.3 on 2025-07-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
