# Generated by Django 5.2.3 on 2025-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0005_category_tags_task_category_task_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tasks', models.ManyToManyField(to='to_do_app.task')),
            ],
        ),
    ]
