# Generated by Django 5.2.3 on 2025-07-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0006_listoftasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
