# Generated by Django 5.2.3 on 2025-07-22 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0007_remove_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listoftasks',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='to_do_app.listoftasks'),
        ),
    ]
